name: Update Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3,9 * * 2"

jobs:
  process:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      USER: hantang
      SRC_NAME: cinephile-code

    steps:
      - uses: actions/checkout@v4

      - name: Checkout src repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.USER }}/${{ env.SRC_NAME }}
          token: ${{ secrets.GH_TOKEN }}
          path: ${{ env.SRC_NAME }}
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Run script letterboxd
        if: github.event.schedule == '0 3,9 * * 2'
        run: |
          pushd ${{ env.SRC_NAME }} && 
          bash scripts/run-top.sh letterboxd &&
          popd

      - name: Git auto commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit_message: Automated update by github action
          # commit_options: '--no-verify --signoff'
          push_options: "--force"
          file_pattern: "*.json"
